CREATE USER gdal WITH PASSWORD 'gdal';

CREATE DATABASE gdal OWNER gdal;

GRANT ALL PRIVILEGES ON DATABASE gdal TO gdal;

\c gdal;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;