CREATE USER osm2pgsql WITH PASSWORD 'osm2pgsql';
CREATE USER mapnik WITH PASSWORD 'mapnik';

CREATE DATABASE mapnik OWNER mapnik;

GRANT ALL PRIVILEGES ON DATABASE mapnik TO osm2pgsql;
GRANT ALL PRIVILEGES ON DATABASE mapnik TO mapnik;

\c mapnik;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;

GRANT ALL PRIVILEGES ON SCHEMA public TO osm2pgsql;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO osm2pgsql;