[global]
daemonize = no

; the [www] ini section below is for backwards compatibility and will be removed in 8.6+
[www]
listen=/run/php/php.sock

listen.owner=www-data
listen.group=www-data

listen.mode=0666