services:
  php:
    build: ./php
    working_dir: /var/www/html
    volumes:
      - ../public:/var/www/html:ro
      - php:/run/php
    networks:
      - php
      - postgres
    ports:
      - "9000:9000"
  httpd:
    image: httpd:2.4.66-trixie
    working_dir: /var/www/html
    volumes:
      - ../public:/var/www/html:ro
      - ./httpd/extra/proxy-php.conf:/usr/local/apache2/conf/extra/proxy-php.conf:ro
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - php:/run/php
    networks:
      - php
    ports:
      - "80:80"
      - "443:443"
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql
      - ./postgres/postgis.sql:/docker-entrypoint-initdb.d/postgis.sql
    networks:
      - postgres
    ports:
      - "5432:5432"

volumes:
  php:
  postgres:
networks:
  php:
  postgres: