services:
  php:
    build: ./php
    volumes:
      - ../public:/var/www/html
      - php:/run/php
      - mapnik:/var/lib/mapnik
      - gdal:/var/lib/gdal
    depends_on:
      - postgres
      - mapnik
      - gdal
    networks:
      - php
      - postgres
      - mapnik
      - gdal
  httpd:
    build: ./httpd
    volumes:
      - ../public:/var/www/html
      - php:/run/php
    depends_on:
      - php
    networks:
      - php
    ports:
      - "80:80"
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql
    networks:
      - postgres
    ports:
      - "5432:5432"
  mapnik:
    build: ./mapnik
    volumes:
      - ./mapnik/osm/oregon.osm.pbf:/var/tmp/osm/oregon.osm.pbf
      - mapnik:/var/lib/mapnik
    networks:
      - mapnik
      - postgres
    depends_on:
      - postgres
  gdal:
    build: ./gdal
    volumes:
      - gdal:/var/lib/gdal
    networks:
      - gdal
    depends_on:
      - postgres

volumes:
  php:
  postgres:
  mapnik:
  gdal:
networks:
  php:
  postgres:
  mapnik:
  gdal: